### ISSUE TITLE
NoSuchElement on checkExtraStartConditions

### ISSUE THREAD

**Issue by mvinet** [Thelnfamous1/All-Bark-All-Bite#10]
Hello ! 
We are currently using this mod on a server modpack with friends (modpack : SteamPunk LTS) 

And we have this exception when a friend is connecting on a chunk with a wolf (?) and the server immediatly shutdown after that

```java
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at TRANSFORMER/all_bark_all_bite@1.19.2-0.9.3/com.infamous.all_bark_all_bite.common.behavior.pet.DefendLikedPlayer.checkExtraStartConditions(DefendLikedPlayer.java:35)
	at TRANSFORMER/all_bark_all_bite@1.19.2-0.9.3/com.infamous.all_bark_all_bite.common.behavior.pet.DefendLikedPlayer.m_6114_(DefendLikedPlayer.java:17)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.ai.behavior.RunIf.m_6114_(RunIf.java:53)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.ai.behavior.Behavior.m_22554_(Behavior.java:45)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.ai.Brain.m_21957_(Brain.java:516)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.ai.Brain.m_21865_(Brain.java:475)
	at TRANSFORMER/all_bark_all_bite@1.19.2-0.9.3/com.infamous.all_bark_all_bite.common.entity.wolf.WolfHooks.onWolfUpdate(WolfHooks.java:40)
	at TRANSFORMER/all_bark_all_bite@1.19.2-0.9.3/com.infamous.all_bark_all_bite.common.ForgeEventHandler.onLivingUpdate(ForgeEventHandler.java:152)
	at TRANSFORMER/all_bark_all_bite@1.19.2-0.9.3/com.infamous.all_bark_all_bite.common.__ForgeEventHandler_onLivingUpdate_LivingTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.3.9/net.minecraftforge.common.ForgeHooks.onLivingTick(ForgeHooks.java:315)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2251)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.Mob.m_8119_(Mob.java:318)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.animal.Wolf.m_8119_(Wolf.java:190)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.Level.m_46653_(Level.java:457)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by mvinet** [comment]
I fixed it on my side, 

the problem is located here:  `TrustAi.getLikedPlayer(mob).get();`
When my friend is offline, `getLikedPlayer(mob)` is empty

**Comment by AshfordMonte** [comment]
Can confirm this issue is happening consistently. Anytime the pet owner is offline and the wolf is loaded the server crashes.
